mysite/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (
                    MyLogoutView,
                    AboutMeView,
                    RegisterView,
                    UsersListView,
                    UpdateProfileView,
                    AboutUserView,
                    HelloWorldView,

)

app_mame = 'accounts'
urlpatterns = [
    path('login/',
         LoginView.as_view(template_name="accounts/login.html", redirect_authenticated_user=True),
         name='login'
         ),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path("register/", RegisterView.as_view(), name="register"),
    path("users-list/", UsersListView.as_view(), name="users_list"),
    path("about-me/", AboutMeView.as_view(), name="about_me"),
    # path("about-me/profile_update_form/", UpdateProfileView.as_view(), name="profile_update_form"),
    path("about-user/<int:pk>/", AboutUserView.as_view(), name="about_user"),
    path("about-user/<int:pk>/profile_update_form/", UpdateProfileView.as_view(), name="profile_update_form"),
    path("hello/", HelloWorldView.as_view(), name="hello")
]

mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (
                    login_view,
                    logout_view,
                    MyLogoutView,
                    get_cookie_view,
                    set_cookie_view,
                    get_session_view,
                    set_session_view,
                    AboutMeView,
                    # RegisterView,
                    FooBarView,

)

app_mame = 'myauth'
urlpatterns = [
    #path('login/', login_view, name='login'),
    #path('logout/', logout_view, name='logout'),
    # path('login/',
    #      LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True),
    #      name='login'
    #      ),
    # path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookie/get/', get_cookie_view, name='get_cookie'),
    path('cookie/set/', set_cookie_view, name='set_cookie'),
    path('session/get/', get_session_view, name='get_session'),
    path('session/set/', set_session_view, name='set_session'),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    # path("register/", RegisterView.as_view(), name="register"),
    path('foo-bar/', FooBarView.as_view(), name='foo_bar'),

]

mysite/mysite/urls.py
from http.cookiejar import debug

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
                                   SpectacularSwaggerView)
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include(('requestdataapp.urls', 'requestdataapp'), namespace='requestdataapp')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include(('myapiapp.urls', 'myapiapp'), namespace='myapiapp')),
    path('blogapi/', include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('myblogapi/', include(('myblogapp.urls', 'myblogapp'), namespace='myblogapp')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )

]
urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('shop/', include(('shopapp.urls', 'shopapp'), namespace='shopapp')),

)

print(urlpatterns)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


def avatar_directory_path(instance: "User", filename: str) -> str:
    return "user/user-{pk}/avatar/{filename}".format(
        pk=instance.user.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to=avatar_directory_path,
    )


# def account_avatar_directory_path(instance: "Profile", filename: str) -> str:
#     return "user/user-{pk}/avatar/{filename}".format(
#         pk=instance.user.pk,
#         filename=filename,
#     )
#
#
# class ProfileAvatar(models.Model):
#     user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="avatar")
#     avatar = models.ImageField(null=True, blank=True, upload_to=account_avatar_directory_path)

mysite/accounts/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "user", "avatar",

mysite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.http import HttpRequest, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView
from django.utils.translation import gettext_lazy as _, ngettext

from .models import Profile, User


class HelloWorldView(View):
    welcome_message = _("Welcome Hello world!")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"
        )

# def login_view(request: HttpRequest):
#     if request.method == "GET":
#         if request.user.is_authenticated:
#             return redirect('/admin/')
#         return render(request, 'accounts/login.html')
# 
#     username = request.POST["username"]
#     password = request.POST["password"]
# 
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         return redirect('/admin/')
# 
#     return render(request, 'accounts/login.html', {"error": "Invalid login credentials"})
# 
# 
# def logout_view(request: HttpRequest):
#     logout(request)
#     return redirect(reverse("accounts:login"))
# 
# 
class MyLogoutView(LogoutView):
    next_page = reverse_lazy("accounts:login")


# class AboutMeView(TemplateView):
#     template_name = "accounts/about-me.html"
#     model = Profile
#     context_object_name = "profile"
#
    # def get_success_url(self):
    #     return reverse(
    #         "accounts:about_me",
    #         kwargs={"pk": self.object.pk},
    #     )


class UsersListView(ListView):
    template_name = 'accounts/users-list.html'
    context_object_name = "users"
    queryset = User.objects.select_related('profile')
    # queryset = Product.objects.filter(archived=False)


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:about_me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)

        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response

    # def get_success_url(self):
    #     return reverse(
    #         "accounts:about_me",
    #         kwargs={"pk": self.object.pk},
    #     )


class UpdateProfileView(UpdateView):
    model = Profile
    fields = "user", "bio", "avatar"
    # form_class = ProfileForm
    template_name_suffix = "_update_form"

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     for avatar in form.files.get():
    #         Profile.objects.create(
    #             user=self.object,
    #             avatar=avatar,
    #         )
    #     return response

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        user = User.objects.select_related("profile").get(pk=pk)
        try:
            return user.profile
        except Profile.DoesNotExist:
            return Profile.objects.create(user=user)

    def get_success_url(self):
        return reverse(
            "accounts:about_user",
            kwargs={"pk": self.kwargs.get(self.pk_url_kwarg)},
        )


class AboutMeView(UpdateView):
    template_name = "accounts/about-me.html"
    model = Profile
    fields = "bio", "avatar",

    success_url = reverse_lazy("accounts:about_me")

    def get_object(self, queryset=None):
        return self.request.user.profile


class AboutUserView(DetailView):
    template_name = "accounts/about-user.html"
    model = User
    queryset = User.objects.select_related("profile")
    context_object_name = "user"

    success_url = reverse_lazy("accounts:about_user")

mysite/accounts/templates/accounts/about-me.html
{% extends 'accounts/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <h2>Detail</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        {% if user.profile.avatar %}
            <h3>Аватар</h3>
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
        {% else %}
            <div>No avatar yet
            </div>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

    <div>
        <br>
        <a href="{% url 'accounts:users_list' %}">Users list</a>
    </div>

{% endblock %}

mysite/accounts/templates/accounts/about-user.html
{% extends 'accounts/base.html' %}

{% block title %}
    About user
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated  %}
        <h2>Detail</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        <h3>Avatar</h3>
        <div>
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
            {% else %}
                <div>No avatar yet
                </div>
            {% endif %}
            {% if request.user.is_staff or user == request.user %}
                <div>
                    <a href="{% url 'accounts:profile_update_form' pk=user.pk %}">Update profile</a>
                </div>
            {% endif %}
        </div>


    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

    <div>
        <br>
        <a href="{% url 'accounts:users_list' %}">Back to users list</a>
    </div>

{% endblock %}

mysite/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
<!--        <p style="color: red">-->
<!--            {{ error }}-->
<!--        </p>-->
<!--        <p>-->
<!--            <label for="username">Username</label>-->
<!--            <input type="text" id="username" name="username" required>-->
<!--        </p>-->
<!--        <p>-->
<!--            <label for="password">Password</label>-->
<!--            <input type="text" id="password" name="password" required>-->
<!--        </p>-->
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block title %}
  Logout
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/profile_update_form.html
{% extends 'accounts/base.html' %}

{% block title %}
    Update Avatar
{% endblock %}

{% block body %}
    {{ '<h1>Update Profile:</h1>'}}

    <div>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

    <br>
    <div>
        <a href="{% url 'accounts:about_user' pk=user.pk %}">
            Back to info about user</a>
    </div>
{% endblock %}

mysite/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

{% endblock %}

mysite/accounts/templates/accounts/users-list.html
{% extends 'accounts/base.html' %}

{% block title %}
    Users List
{% endblock %}

{% block body %}
        {{ '<h1>Users:</h1>'}}
        <div>
            {% if not users %}
                <h3>Пользователи отсутствуют</h3>
            {% else %}
                <ul>
                    {% for user in users %}
                        <li>
                            <div><a href="{% url 'accounts:about_user' pk=user.pk %}">
                                {{ user.pk }}. UserName: {{ user.username }}</a></div>

                            {% if user.profile.avatar %}
                                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
                            {% endif %}
                            <br>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
{% endblock %}