mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (
                    login_view,
                    logout_view,
                    MyLogoutView,
                    get_cookie_view,
                    set_cookie_view,
                    get_session_view,
                    set_session_view,
                    AboutMeView,
                    # RegisterView,
                    FooBarView,

)

app_mame = 'myauth'
urlpatterns = [
    #path('login/', login_view, name='login'),
    #path('logout/', logout_view, name='logout'),
    # path('login/',
    #      LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True),
    #      name='login'
    #      ),
    # path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookie/get/', get_cookie_view, name='get_cookie'),
    path('cookie/set/', set_cookie_view, name='set_cookie'),
    path('session/get/', get_session_view, name='get_session'),
    path('session/set/', set_session_view, name='set_session'),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    # path("register/", RegisterView.as_view(), name="register"),
    path('foo-bar/', FooBarView.as_view(), name='foo_bar'),

]

mysite/mysite/urls.py
from http.cookiejar import debug

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
                                   SpectacularSwaggerView)
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include(('requestdataapp.urls', 'requestdataapp'), namespace='requestdataapp')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include(('myapiapp.urls', 'myapiapp'), namespace='myapiapp')),
    path('blogapi/', include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('myblogapi/', include(('myblogapp.urls', 'myblogapp'), namespace='myblogapp')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )

]
urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('shop/', include(('shopapp.urls', 'shopapp'), namespace='shopapp')),

)

print(urlpatterns)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from rest_framework.routers import DefaultRouter

from .views import (
                    ShopIndexView,
                    GroupsListView,
                    ProductDetailsView,
                    ProductsListView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    OrdersListView,
                    OrderDetailsView,
                    OrderCreateView,
                    OrderUpdateView,
                    OrderDeleteView,
                    ProductsDataExportView,
                    OrdersDataExportView,
                    ProductViewSet,
                    OrderViewSet,
                    LatestProductsFeed,
                    UserOrdersListView,

                    )

app_mame = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    # path('', cache_page(60 * 3)(ShopIndexView.as_view()), name='index'),
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products_export'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders_export'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/', OrderDetailsView.as_view(), name='order_details'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/archive/', OrderDeleteView.as_view(), name='order_delete'),

    path("products/latest/feed/", LatestProductsFeed(), name="product-feed"),

    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='users_orders'),

]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "product/product-{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине

    Картинки тут: :model:`shopapp.ProductImage`
    """
    class Meta:
        ordering = ["name", "price"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, null=False, on_delete=models.PROTECT)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.pk})


def product_image_directory_path(instance: "Product", filename: str) -> str:
    return "product/product-{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(null=True, blank=True, upload_to=product_image_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    """
    Модель Order - заказы в интернет-магазине.

    Товары тут: :model:`shopapp.product`
    """
    class Meta:
        ordering = ["user", "delivery_address"]
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts')

mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django import forms

from .models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "discount", "description", "preview"

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True})
    )


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "user", "products"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "name",


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} detail
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }} detail</h1>
    <div>
        <p>Order by: {% firstof order.user.first_name|add:" "|add:order.user.last_name order.user.username %} </p>
        <p>Delivery_address: {{ order.delivery_address }}</p>
        <p>Promocode: {% firstof order.promocode 'no promocode' %}</p>
        <div>
            Products in the order:
            <ul>
                {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_update' pk=order.pk%}">Update order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:order_delete' pk=order.pk%}">Delete order</a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete order {{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete order #{{ object.pk }}?</h1>
    <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk%}">
            Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders List
{% endblock %}

{% block body %}
    {{ '<h1 style="text-align: center;">Orders:</h1>'}}
    <div>
        {% if not object_list %}
            <h3>Заказы отсутствуют</h3>
        {% else %}
            <ul>
                {% for order in object_list %}
                    <div>
                        <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">
                            Details #{{ order.pk }}</a></p>
                        <p>Order by: {% firstof order.user.first_name|add:" "|add:order.user.last_name order.user.username %} </p>
                        <p>Delivery_address: {{ order.delivery_address }}</p>
                        <p>Promocode: {% firstof order.promocode 'no promocode' %}</p>
                        <div>
                            Товары в заказе:
                            <ul>
                                {% for product in order.products.all %}
                                    <li>{{ product.name }} for ${{ product.price }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <br>
    {% if perms.shopapp.add_order %}
        <div>
            <a href="{% url 'shopapp:order_create' %}">Create a new order</a>
        </div>
    {% endif %}
    {% if user.is_superuser %}
        <div>
            <a href="{% url 'shopapp:orders_export' %}">Export orders</a>
        </div>
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update Order
{% endblock %}

{% block body %}
    {{ '<h1>Update order:</h1>'}}

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk%}">
            Back to order #{{ order.pk}}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
       Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Product details' %}
{% endblock %}

{% block body %}
    {% blocktranslate with name=product.name description=product.description price=product.price discount=product.discount archived=product.archived created_by=product.created_by %}
    <h1>Product {{ name }} </h1>
    <div>Description: {{ description }}</div>
    <div>Price: {{ price }}</div>
    <div>Discount: {{ discount }}</div>
    <div>Archived: {{ archived }}</div>
    <div>created_by: {{ created_by }}</div>
    {% endblocktranslate %}

    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}
    <h3>{% translate 'Images' %}</h3>
    <div>
        {% blocktranslate count images_count=product.images.all|length%}
            There is only one image.
            {% plural %}
            There are {{ images_count }} images.
        {% endblocktranslate %}
        {% for img in product.images.all %}
            <div>
                <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                <div>{{ img.description }}</div>
            </div>
        {% empty %}
            <div>{% translate 'No images yet' %}</div>
        {% endfor %}
    </div>

    <br>
    {% if user.is_superuser or perms.shopapp.change_product and product.created_by == user %}
        <div>
            <a href="{% url 'shopapp:product_update' pk=product.pk%}">
                {% translate 'Update product' %}</a>
        </div>
        <div>
            <a href="{% url 'shopapp:product_delete' pk=product.pk%}">
                {% translate 'Archive product' %}</a>
        </div>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            {% translate 'Back to products list' %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive product {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive product {{ object.name }}?</h1>
    <div>
        <a href="{% url 'shopapp:product_details' pk=product.pk%}">
            Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create Product
{% endblock %}

{% block body %}
    {{ '<h1>Create a new product:</h1>'}}

    <div>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    </div>

    <br>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{ product.pk }}
{% endblock %}

{% block body %}
  <h1>Product <strong>{{ product.name }}</strong></h1>
  <div>
    <div>Description: <em>{{ product.description }}</em></div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Archived: {{ product.archived }}</div>

    {% if product.preview %}
      <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}

    <h3>Images:</h3>
    <div>
      {% for img in product.images.all %}
        <div>
          <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
          <div>{{ img.description }}</div>
        </div>
      {% empty %}
        <div>No images uploaded yet</div>
      {% endfor %}

    </div>
  </div>
  <div>
    <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products List' %}
{% endblock %}

{% block body %}
    <h1> {% translate 'Products' %}:</h1>
    <div>
        {% if not products %}
            {% if perms.shopapp.add_product %}
                <div>
                    {% url 'shopapp:product_create' as create_product_url %}
                    {% blocktranslate %}
                    <h3>No products yet</h3>
                    <a href="{{ create_product_url }}">
                        Create a new one</a>
                    {% endblocktranslate %}
                </div>
            {% else %}
                <h3>{% translate 'No products yet' %}</h3>
            {% endif %}
        {% else %}
            <div>
                {% blocktranslate count products_count=products|length%}
                    There is only one product.
                    {% plural %}
                    There are {{ products_count }} products.
                {% endblocktranslate %}
            </div>
            <ul>
                {% for product in products %}
                    <li>
                        <div><a href="{% url 'shopapp:product_details' pk=product.pk %}">
                            {% translate 'Name' context 'product name' %}: {{ product.name }}</a></div>
                        <div>{% translate 'Price' %}: {{ product.price }}</div>
                        {% translate 'no discount' as no_discount %}
                        <div>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</div>

                        {% if product.preview %}
                            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                        {% endif %}
                        <br>
                    </li>
                {% endfor %}
            </ul>
            {% if perms.shopapp.add_product %}
                <div>
                    <a href="{% url 'shopapp:product_create' %}">
                        {% translate 'Create a new product' %}</a>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
  <li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">
       Import CSV
    </a>
  </li>
  {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    {{ '<h1>Shop Index!</h1>'}}

    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name|title }} for ${{ price }}</li>
                {% if price|divisibleby:"3" %}
                    <span>Вам скидка, так как цена делится на 3!<br>

                    {{ "Чтобы получить скидку, пришлите свой e-mail по адресу: foo@example.com"|urlize }}</span>
                {% endif %}
            {% empty %}
                No products here
            {% endfor %}
        </ul>
    </div>

    <div>
        <strong>
            You have {{ items }} item{{ items|pluralize }}
            You have {{ items }} class{{ items|pluralize:"es" }}
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>


    <div>
        Time running: {{time_running}}
    </div>
    {% cache 100 loren %}
        <div>
            {% lorem 2 p random %}
        </div>
    {% endcache %}
{% endblock %}