mysite/blogapp/urls.py
from django.urls import path, include

from .views import (
                    ArticleListView,
)

app_mame = 'blogapp'

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles_list'),
]

mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (
                    login_view,
                    logout_view,
                    MyLogoutView,
                    get_cookie_view,
                    set_cookie_view,
                    get_session_view,
                    set_session_view,
                    AboutMeView,
                    # RegisterView,
                    FooBarView,

)

app_mame = 'myauth'
urlpatterns = [
    #path('login/', login_view, name='login'),
    #path('logout/', logout_view, name='logout'),
    # path('login/',
    #      LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True),
    #      name='login'
    #      ),
    # path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookie/get/', get_cookie_view, name='get_cookie'),
    path('cookie/set/', set_cookie_view, name='set_cookie'),
    path('session/get/', get_session_view, name='get_session'),
    path('session/set/', set_session_view, name='set_session'),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    # path("register/", RegisterView.as_view(), name="register"),
    path('foo-bar/', FooBarView.as_view(), name='foo_bar'),

]

mysite/myblogapp/urls.py
from django.urls import path

from .views import ArticlesListView, ArticleDetailView, LatestArticlesFeed

appname = 'myblogapp'

urlpatterns = [
    path("articles/", ArticlesListView.as_view(), name="articles"),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="article"),
    path("articles/latest/feed/", LatestArticlesFeed(), name="article-feed"),
]

mysite/mysite/urls.py
from http.cookiejar import debug

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
                                   SpectacularSwaggerView)
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include(('requestdataapp.urls', 'requestdataapp'), namespace='requestdataapp')),
    path('myauth/', include(('myauth.urls', 'myauth'), namespace='myauth')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include(('myapiapp.urls', 'myapiapp'), namespace='myapiapp')),
    path('blogapi/', include(('blogapp.urls', 'blogapp'), namespace='blogapp')),
    path('myblogapi/', include(('myblogapp.urls', 'myblogapp'), namespace='myblogapp')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )

]
urlpatterns += i18n_patterns(
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('shop/', include(('shopapp.urls', 'shopapp'), namespace='shopapp')),

)

print(urlpatterns)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/blogapp/models.py
from django.db import models


class Author(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=100, db_index=True)
    bio = models.TextField(null=False, blank=True)

    def __str__(self):
        return f"Author (pk={self.pk}, name={self.name!r})"


class Category(models.Model):

    name = models.CharField(max_length=40, db_index=True)

    def __str__(self):
        return f"Category (pk={self.pk}, name={self.name!r})"


class Tag(models.Model):

    name = models.CharField(max_length=20, db_index=True)

    def __str__(self):
        return f"Tag (pk={self.pk}, name={self.name!r})"


class Article(models.Model):

    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField(null=False, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, null=False, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=False, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name="tags_name")

    def __str__(self):
        return f"Article (pk={self.pk}, title={self.title!r}, author={self.author.name!r})"

mysite/blogapp/views.py
from django.shortcuts import render

from django.views.generic import (ListView)

from blogapp.models import Article


class ArticleListView(ListView):
    template_name = 'blogapp/articles_list.html'
    context_object_name = "article"
    queryset = (
                Article.objects.defer("content").
                select_related("author").
                select_related("category").
                prefetch_related("tags")
                )

mysite/blogapp/templates/blogapp/article_detail.html
{% extends 'blogapp/base.html' %}

{% block title %}
  Article #{{ object.pk }}
{% endblock %}


{% block body %}
  <h1>Article</h1>
  <div>
    <p>{{ article.title }}</p>
    <p>Published: {{ article.published_at }}</p>
    <p>Body: {{ article.body }}</p>
  </div>
  <div>
    <a href="{% url 'blogapp:articles' %}">Back to articles list</a>
  </div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_list.html
{% extends 'blogapp/base.html' %}

{% block title %}
  Articles
{% endblock %}


{% block body %}
  <h1>Articles</h1>
  {% if object_list %}
    <div>
    {% for article in object_list %}
      <div>
        <p>
          <a href="{% url 'blogapp:article' pk=article.pk %}">{{ article.title }}</a>
        </p>
        <p>Published: {{ article.published_at }}</p>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <h3>No published articles yet</h3>
  {% endif %}
{% endblock %}

mysite/blogapp/templates/blogapp/articles_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Articles List
{% endblock %}

{% block body %}
        {{ '<h1>Articles:</h1>'}}
    <div>
        {% if not object_list %}
            <h3>No articles yet</h3>
        {% else %}
            <ul>
                {% for article in object_list %}
                    <div>
                        <h1>Article #{{ article.pk }} detail</h1>
                        <p>Author: {{ article.author.name }} </p>
                        <p>Title: {{ article.title }} </p>
                        <p>Date of publication: {{ article.pub_date }}</p>
                        <p>category: {{ article.category.name }}</p>
                        <div>
                            Tags:
                            <ul>
                                {% for tag in article.tags.all %}
                                    <li>{{ tag.name }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <br>

{% endblock %}

mysite/blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>